### ISSUE TITLE
Actors Abstract Class

### ISSUE THREAD

**Issue by nanoterran** [zombie-simulation-team/Zombie-Simulation#6]
Write an abstract class for the actors in the simulation following the design spec. Actor is a base class for the zombie class and the human class.

**Design spec file -** https://drive.google.com/open?id=1MEfedzkgF9tB7eAgHDo8ISduyml88pqpAVaaVSba6kQ
- [ ] move() function is pure virtual
- [ ] attack() function is pure virtual
- [ ] Tested

**Comment by theawesomechin** [comment]
Alex Picked this up
